version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/e2e"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/e2e"
    schedule:
      interval: "weekly"

